add a commandline to convert p12 into pem
LinkValue/MobileNotifBundle pull request #22
Opened 2017-01-24 09:42 UTC by Amitsouko

Add a commandline to do a proper .pem certificate.

2017-01-24 10:04 UTC, Oliboy50 requested changes

2017-01-24 10:04 UTC, Oliboy50 commented on Resources/doc/getting_started.md
> +```
this should be after the `Examples` section IMHO

maybe the developer will receive a proper `.pem` file already, so he won't have to read this

2017-01-24 10:04 UTC, Oliboy50 commented on Resources/doc/getting_started.md
> +### Transform your certificate .p12 into a .pem
This is iOS specific, it must be mention somewhere

2017-01-25 12:25 UTC, Amitsouko commented on Resources/doc/getting_started.md
> +### Transform your certificate .p12 into a .pem
moved

2017-01-25 12:25 UTC, Amitsouko commented on Resources/doc/getting_started.md
> +```
moved

2017-01-25 13:21 UTC, Oliboy50 approved these changes

2017-01-25 13:21 UTC, merged